import Fluent
import SQLKit

struct ChangeIDsToIdentity: AsyncMigration {
    // Tables that already have GENERATED BY DEFAULT identity
    private let alreadyIdentity = Set([
        "business_type", "canton", "council", "department", "faction",
        "party", "person_interest", "proposition", "subject_business",
        "sync_status", "user"
    ])

    // Tables with user-supplied IDs that need identity added
    private let needsIdentity = [
        "business", "meeting", "member_council", "session",
        "subject", "transcript", "vote", "voting"
    ]

    func prepare(on database: Database) async throws {
        guard let sql = database as? SQLDatabase else { return }

        for table in needsIdentity {
            // Set the sequence to start after the max existing ID
            let maxID = try await sql.raw("""
                SELECT COALESCE(MAX("id"), 0) + 1 AS next_val FROM "\(raw: table)"
                """)
                .first(decodingColumn: "next_val", as: Int.self) ?? 1

            try await sql.raw("""
                ALTER TABLE "\(raw: table)"
                ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (START WITH \(raw: String(maxID)))
                """).run()
        }
    }

    func revert(on database: Database) async throws {
        guard let sql = database as? SQLDatabase else { return }

        for table in needsIdentity {
            try await sql.raw("""
                ALTER TABLE "\(raw: table)"
                ALTER COLUMN "id" DROP IDENTITY IF EXISTS
                """).run()
        }
    }
}
