import Fluent
import SQLKit

struct CreateTranscriptEmbeddings: AsyncMigration {
    func prepare(on database: Database) async throws {
        let sql = database as! SQLDatabase

        // Note: pgvector extension must be created by a superuser:
        //   psql -U postgres -d politscore -c "CREATE EXTENSION IF NOT EXISTS vector;"

        // Create transcript_embedding table with vector column
        try await sql.raw("""
            CREATE TABLE "transcript_embedding" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "transcript_id" INTEGER NOT NULL REFERENCES "transcript"("id"),
                "chunk_index" INTEGER NOT NULL DEFAULT 0,
                "chunk_text" TEXT NOT NULL,
                "embedding" vector(768) NOT NULL,
                UNIQUE("transcript_id", "chunk_index")
            )
        """).run()

        // Create HNSW index for fast cosine similarity search
        try await sql.raw("""
            CREATE INDEX "idx_transcript_embedding_vector"
            ON "transcript_embedding" USING hnsw ("embedding" vector_cosine_ops)
        """).run()
    }

    func revert(on database: Database) async throws {
        let sql = database as! SQLDatabase
        try await sql.raw("""
            DROP TABLE IF EXISTS "transcript_embedding"
        """).run()
    }
}
