import Fluent

struct CreateInitialSchema: AsyncMigration {
    func prepare(on database: Database) async throws {
        // Sessions
        try await database.schema("sessions")
            .field("id", .int, .identifier(auto: false))
            .field("session_name", .string)
            .field("title", .string, .required)
            .field("abbreviation", .string)
            .field("start_date", .datetime)
            .field("end_date", .datetime)
            .field("modified", .datetime)
            .create()

        // Councils
        try await database.schema("councils")
            .field("id", .int, .identifier(auto: true))
            .field("name", .string, .required)
            .field("abbreviation", .string)
            .unique(on: "name")
            .create()

        // Parties
        try await database.schema("parties")
            .field("id", .int, .identifier(auto: true))
            .field("name", .string)
            .field("abbreviation", .string, .required)
            .unique(on: "abbreviation")
            .create()

        // Factions
        try await database.schema("factions")
            .field("id", .int, .identifier(auto: true))
            .field("name", .string)
            .field("abbreviation", .string, .required)
            .unique(on: "abbreviation")
            .create()

        // Cantons
        try await database.schema("cantons")
            .field("id", .int, .identifier(auto: true))
            .field("name", .string)
            .field("abbreviation", .string, .required)
            .unique(on: "abbreviation")
            .create()

        // MemberCouncils
        try await database.schema("member_councils")
            .field("id", .int, .identifier(auto: false))
            .field("person_number", .int, .required)
            .field("first_name", .string, .required)
            .field("last_name", .string, .required)
            .field("official_name", .string)
            .field("gender", .string)
            .field("active", .bool, .required)
            .field("date_of_birth", .datetime)
            .field("date_joining", .datetime)
            .field("date_leaving", .datetime)
            .field("date_election", .datetime)
            .field("marital_status", .string)
            .field("number_of_children", .int)
            .field("birth_place_city", .string)
            .field("birth_place_canton", .string)
            .field("citizenship", .string)
            .field("military_rank", .string)
            .field("nationality", .string)
            .field("mandates", .sql(raw: "TEXT"))
            .field("additional_mandate", .sql(raw: "TEXT"))
            .field("additional_activity", .sql(raw: "TEXT"))
            .field("occupation_name", .sql(raw: "TEXT"))
            .field("employer", .sql(raw: "TEXT"))
            .field("job_title", .sql(raw: "TEXT"))
            .field("modified", .datetime)
            .field("council_id", .int, .references("councils", "id"))
            .field("party_id", .int, .references("parties", "id"))
            .field("faction_id", .int, .references("factions", "id"))
            .field("canton_id", .int, .references("cantons", "id"))
            .create()

        // BusinessTypes
        try await database.schema("business_types")
            .field("id", .int, .identifier(auto: true))
            .field("name", .string, .required)
            .field("abbreviation", .string)
            .unique(on: "name")
            .create()

        // Businesses
        try await database.schema("businesses")
            .field("id", .int, .identifier(auto: false))
            .field("business_short_number", .string)
            .field("title", .string, .required)
            .field("business_status_text", .string)
            .field("business_status_date", .datetime)
            .field("submission_date", .datetime)
            .field("submitted_by", .string)
            .field("description", .sql(raw: "TEXT"))
            .field("submission_council_name", .string)
            .field("responsible_department_name", .string)
            .field("responsible_department_abbreviation", .string)
            .field("tag_names", .sql(raw: "TEXT"))
            .field("modified", .datetime)
            .field("session_id", .int, .required, .references("sessions", "id"))
            .field("business_type_id", .int, .references("business_types", "id"))
            .create()

        // Meetings
        try await database.schema("meetings")
            .field("id", .int, .identifier(auto: false))
            .field("meeting_number", .int)
            .field("session_id", .int, .required, .references("sessions", "id"))
            .field("council", .int)
            .field("council_name", .string)
            .field("council_abbreviation", .string)
            .field("date", .datetime)
            .field("begin", .string)
            .field("meeting_order_text", .sql(raw: "TEXT"))
            .field("sort_order", .int)
            .field("session_name", .string)
            .create()

        // Subjects
        try await database.schema("subjects")
            .field("id", .int, .identifier(auto: false))
            .field("id_meeting", .int)
            .field("sort_order", .int)
            .field("verbalix_oid", .int)
            .create()

        // SubjectBusinesses
        try await database.schema("subject_businesses")
            .field("id", .int, .identifier(auto: true))
            .field("id_subject", .int)
            .field("business_number", .int)
            .field("business_short_number", .string)
            .field("title", .string)
            .field("sort_order", .int)
            .create()

        // Transcripts
        try await database.schema("transcripts")
            .field("id", .int, .identifier(auto: false))
            .field("person_number", .int)
            .field("speaker_full_name", .string)
            .field("speaker_function", .string)
            .field("text", .sql(raw: "TEXT"))
            .field("meeting_date", .datetime)
            .field("start_time", .datetime)
            .field("end_time", .datetime)
            .field("council_name", .string)
            .field("parl_group_abbreviation", .string)
            .field("canton_abbreviation", .string)
            .field("sort_order", .int)
            .field("type", .int)
            .field("id_subject", .int)
            .create()

        // Votes
        try await database.schema("votes")
            .field("id", .int, .identifier(auto: false))
            .field("business_number", .int)
            .field("business_short_number", .string)
            .field("bill_title", .string)
            .field("subject", .sql(raw: "TEXT"))
            .field("meaning_yes", .string)
            .field("meaning_no", .string)
            .field("vote_end", .datetime)
            .field("session_id", .int, .required, .references("sessions", "id"))
            .create()

        // Votings
        try await database.schema("votings")
            .field("id", .int, .identifier(auto: false))
            .field("vote_id", .int, .required, .references("votes", "id"))
            .field("person_number", .int, .required)
            .field("decision", .int, .required)
            .field("decision_text", .string)
            .create()

        // PersonInterests
        try await database.schema("person_interests")
            .field("id", .int, .identifier(auto: true))
            .field("person_number", .int, .required)
            .field("interest_name", .string)
            .field("interest_type_text", .string)
            .field("function_in_agency_text", .string)
            .field("paid", .bool)
            .field("organization_type_text", .string)
            .create()

        // Propositions
        try await database.schema("propositions")
            .field("id", .int, .identifier(auto: true))
            .field("transcript_id", .int)
            .field("text", .sql(raw: "TEXT"), .required)
            .field("category", .string)
            .field("confidence", .double)
            .field("created_at", .datetime)
            .create()

        // SyncStatuses
        try await database.schema("sync_statuses")
            .field("id", .int, .identifier(auto: true))
            .field("entity_name", .string, .required)
            .field("session_id", .int)
            .field("last_sync_at", .datetime)
            .field("status", .string, .required)
            .field("items_synced", .int, .required)
            .field("error_message", .sql(raw: "TEXT"))
            .create()
    }

    func revert(on database: Database) async throws {
        try await database.schema("sync_statuses").delete()
        try await database.schema("propositions").delete()
        try await database.schema("person_interests").delete()
        try await database.schema("votings").delete()
        try await database.schema("votes").delete()
        try await database.schema("transcripts").delete()
        try await database.schema("subject_businesses").delete()
        try await database.schema("subjects").delete()
        try await database.schema("meetings").delete()
        try await database.schema("businesses").delete()
        try await database.schema("member_councils").delete()
        try await database.schema("cantons").delete()
        try await database.schema("factions").delete()
        try await database.schema("parties").delete()
        try await database.schema("councils").delete()
        try await database.schema("sessions").delete()
    }
}
