-- PoliticoServer Database Schema
-- PostgreSQL 15+
-- Usage: psql -U politscore -d politscore -f schema.sql

-- ============================================================
-- Lookup Tables
-- ============================================================

CREATE TABLE council (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    abbreviation TEXT,
    UNIQUE (name)
);

CREATE TABLE party (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT,
    abbreviation TEXT NOT NULL,
    color        TEXT,
    UNIQUE (abbreviation)
);

CREATE TABLE faction (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT,
    abbreviation TEXT NOT NULL,
    UNIQUE (abbreviation)
);

CREATE TABLE canton (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT,
    abbreviation TEXT NOT NULL,
    UNIQUE (abbreviation)
);

CREATE TABLE department (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    abbreviation TEXT,
    UNIQUE (name)
);

CREATE TABLE business_type (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    abbreviation TEXT,
    UNIQUE (name)
);

-- ============================================================
-- Core Tables
-- ============================================================

CREATE TABLE session (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    abbreviation TEXT,
    start_date   DATE,
    end_date     DATE,
    modified     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE member_council (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          TEXT NOT NULL,
    last_name           TEXT NOT NULL,
    official_name       TEXT,
    gender              TEXT,
    active              BOOLEAN NOT NULL,
    date_of_birth       DATE,
    date_joining        DATE,
    date_leaving        TIMESTAMP WITH TIME ZONE,
    date_election       DATE,
    marital_status      TEXT,
    number_of_children  INTEGER,
    birth_place_city    TEXT,
    birth_place_canton  TEXT,
    citizenship         TEXT,
    military_rank       TEXT,
    nationality         TEXT,
    mandates            TEXT,
    additional_mandate  TEXT,
    additional_activity TEXT,
    occupation_name     TEXT,
    employer            TEXT,
    job_title           TEXT,
    modified            TIMESTAMP WITH TIME ZONE,
    council_id          INTEGER REFERENCES council(id),
    party_id            INTEGER REFERENCES party(id),
    faction_id          INTEGER REFERENCES faction(id),
    canton_id           INTEGER REFERENCES canton(id)
);

CREATE TABLE committee (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL,
    abbreviation      TEXT,
    committee_type    TEXT,
    council_id        INTEGER REFERENCES council(id),
    main_committee_id INTEGER REFERENCES committee(id),
    modified          TIMESTAMP WITH TIME ZONE
);

CREATE TABLE business (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number                    TEXT,
    title                     TEXT NOT NULL,
    status                    TEXT,
    status_date               DATE,
    submission_date           DATE,
    submitted_by              TEXT,
    description               TEXT,
    submitted_text            TEXT,
    reason_text               TEXT,
    federal_council_response  TEXT,
    federal_council_proposal  TEXT,
    tag_names                 TEXT,
    modified                  TIMESTAMP WITH TIME ZONE,
    session_id                INTEGER NOT NULL REFERENCES session(id),
    business_type_id          INTEGER REFERENCES business_type(id),
    submission_council_id     INTEGER REFERENCES council(id),
    responsible_department_id INTEGER REFERENCES department(id),
    submitted_by_council_id   INTEGER REFERENCES member_council(id)
);

CREATE TABLE meeting (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE,
    begin           TEXT,
    sort_order      INTEGER,
    sort_order_text TEXT,
    session_id      INTEGER NOT NULL REFERENCES session(id),
    council_id      INTEGER REFERENCES council(id)
);

CREATE TABLE subject (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order INTEGER,
    meeting_id INTEGER REFERENCES meeting(id)
);

CREATE TABLE subject_business (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order  INTEGER,
    subject_id  INTEGER REFERENCES subject(id),
    business_id INTEGER REFERENCES business(id)
);

CREATE TABLE transcript (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    speaker_function        TEXT,
    text                    TEXT,
    meeting_date            DATE,
    start_time              TIMESTAMP WITH TIME ZONE,
    end_time                TIMESTAMP WITH TIME ZONE,
    sort_order              INTEGER,
    type                    INTEGER,
    propositions_extracted  BOOLEAN NOT NULL DEFAULT FALSE,
    member_council_id       INTEGER REFERENCES member_council(id),
    council_id              INTEGER REFERENCES council(id),
    subject_id              INTEGER REFERENCES subject(id)
);

CREATE TABLE vote (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_title  TEXT,
    subject     TEXT,
    meaning_yes TEXT,
    meaning_no  TEXT,
    vote_end    TIMESTAMP WITH TIME ZONE,
    session_id  INTEGER NOT NULL REFERENCES session(id),
    business_id INTEGER REFERENCES business(id)
);

CREATE TABLE voting (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision          INTEGER NOT NULL,
    decision_text     TEXT,
    vote_id           INTEGER NOT NULL REFERENCES vote(id),
    member_council_id INTEGER REFERENCES member_council(id)
);

CREATE TABLE member_committee (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    function          TEXT,
    modified          TIMESTAMP WITH TIME ZONE,
    member_council_id INTEGER NOT NULL REFERENCES member_council(id),
    committee_id      INTEGER NOT NULL REFERENCES committee(id)
);

CREATE TABLE person_interest (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interest_name          TEXT,
    interest_type_text     TEXT,
    function_in_agency_text TEXT,
    organization_type_text TEXT,
    paid                   BOOLEAN,
    member_council_id      INTEGER REFERENCES member_council(id)
);

CREATE TABLE proposition_subject (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    UNIQUE (name)
);

CREATE TABLE proposition (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text                   TEXT NOT NULL,
    source                 TEXT,
    date_text              TEXT,
    created_at             TIMESTAMP WITH TIME ZONE,
    transcript_id          INTEGER NOT NULL REFERENCES transcript(id),
    proposition_subject_id INTEGER REFERENCES proposition_subject(id)
);

-- ============================================================
-- RAG / Embeddings
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE transcript_embedding (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transcript_id INTEGER NOT NULL REFERENCES transcript(id),
    chunk_index   INTEGER NOT NULL DEFAULT 0,
    chunk_text    TEXT NOT NULL,
    embedding     vector(768) NOT NULL,
    UNIQUE (transcript_id, chunk_index)
);

CREATE INDEX idx_transcript_embedding_vector
    ON transcript_embedding USING hnsw (embedding vector_cosine_ops);

-- ============================================================
-- Application Tables
-- ============================================================

CREATE TABLE "user" (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL,
    email         TEXT,
    created_at    TIMESTAMP WITH TIME ZONE,
    UNIQUE (username)
);

CREATE TABLE sync_status (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name  TEXT NOT NULL,
    session_id   INTEGER,
    last_sync_at TIMESTAMP WITH TIME ZONE,
    status       TEXT NOT NULL,
    items_synced INTEGER NOT NULL,
    error_message TEXT
);
